# Generated by Django 5.0.6 on 2024-07-06 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255)),
                ('folder_path', models.FilePathField(allow_files=False, allow_folders=True, path='D:\\Marcos Herrera\\Documentos 2\\PRUEBA PIS 3\\project_owas\\uploads')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.uploadedfolder')),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_files_scanned', models.IntegerField()),
                ('total_vulnerabilities_found', models.IntegerField()),
                ('uploaded_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='project.uploadedfolder')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('vulnerability_type', models.CharField(choices=[('SQL', 'SQL Injection'), ('XSS', 'Cross-Site Scripting'), ('CSRF', 'Cross-Site Request Forgery'), ('FILE', 'File Inclusion'), ('CMD', 'Command Injection'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=10)),
                ('description', models.TextField()),
                ('detected_code', models.TextField()),
                ('detection_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='project.uploadedfile')),
            ],
        ),
    ]
